version: "3.3"

services:
  db:
    image: postgres:13.2
    restart: unless-stopped
    ports:
    - "5432:5432"
    networks:
      - services
    volumes:
      - ".pg:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: campip
      POSTGRES_USER: root
      POSTGRES_PASSWORD: campip


networks:
  services:
