apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: campip
  name: campip
  namespace: campid-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campip
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: campip
    spec:
      containers:
        - image: localhost.domain:5000/ewestudios/campip:latest
          imagePullPolicy: IfNotPresent
          name: campip
          resources:
            limits:
              cpu: "250m"
              memory: "64Mi"
          readinessProbe:
            timeoutSeconds: 3
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: campip
  name: campip
  namespace: campid-services
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
    - nodePort: 30411
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-node
