CREATE TABLE IF NOT EXISTS locations (
	id SERIAL PRIMARY KEY,
	type_ VARCHAR (30) NOT NULL,
	continent_code TEXT NOT NULL,
	continent_name VARCHAR(60) NOT NULL,
	street VARCHAR (128) NOT NULL,
	city VARCHAR (60) NOT NULL,
	state VARCHAR(60) NOT NULL,
	postal VARCHAR(300) NOT NULL,
	zip VARCHAR(20) NOT NULL,
	zip_code VARCHAR(20) NOT NULL,
	country_code CHARACTER (2) NOT NULL,
	country_name VARCHAR(64) NOT NULL,
	region_code VARCHAR(3) NOT NULL,
	region_name VARCHAR(128) NOT NULL,
	latitude REAL NOT NULL,
	longitude REAL NOT NULL,
	metro_code VARCHAR(128) NOT NULL,
	time_zone VARCHAR(60) NOT NULL,
	area_code VARCHAR(30) NOT NULL,
	from_ip VARCHAR(128) NOT NULL,
	to_ip VARCHAR(128) NOT NULL,
	from_ip_numeric bigint NOT NULL,
	to_ip_numeric bigint NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP
);
