table! {
    locations (id) {
        id -> Int4,
        type_ -> Varchar,
        continent_code -> Text,
        continent_name -> Varchar,
        street -> Varchar,
        city -> Varchar,
        state -> Varchar,
        postal -> Varchar,
        zip -> Varchar,
        zip_code -> Varchar,
        country_code -> Bpchar,
        country_name -> Varchar,
        region_code -> Varchar,
        region_name -> Varchar,
        latitude -> Float4,
        longitude -> Float4,
        metro_code -> Varchar,
        time_zone -> Varchar,
        area_code -> Varchar,
        from_ip -> Varchar,
        to_ip -> Varchar,
        from_ip_numeric -> Int8,
        to_ip_numeric -> Int8,
        created_at -> Timestamp,
        updated_at -> Nullable<Timestamp>,
    }
}
